### ISSUE TITLE
Support enum type

### ISSUE THREAD

**Issue by pallagj** [artygo8/streamlit-sqlalchemy#9]
https://github.com/artygo8/streamlit-sqlalchemy/blob/94e5fe188981551d32b07b539d2bcf3d72caed30/src/streamlit_sqlalchemy/mixin.py#L421

Here would be nice to support enum type, something like this:
```python
        if isinstance(column.type, Enum):
            options = list(column.type.enum_class)
            default = get_default_value(column, default=options[0])

            def selectbox(label, value=None):
                value = value if value is not None else default
                index = options.index(value)
                return st.selectbox(label, options=options, index=index, format_func=lambda x: x.name)

            return selectbox
```

**Comment by artygo8** [comment]
Absolutely! Thanks for your contribution!Feel free to open a PR to which I can add the relevant tests if you want.
Otherwise, I can make the PR.
